/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 */

package com.huawei.hicampus.mate.matecampusclaw.codingagent.runtimeapi.error;

/**
 * Runtime HTTP V1 的稳定错误码。
 *
 * @version [br_eCampusCore 25.1.0_Next, 2026/08/18]
 * @since [br_eCampusCore 25.1.0_Next]
 */
public enum RuntimeErrorCode {
    INVALID_AGENT_ID,
    INVALID_SESSION_ID,
    UNAUTHENTICATED,
    AUTH_CREDENTIAL_CONFLICT,
    AGENT_NOT_FOUND,
    AGENT_NOT_AVAILABLE,
    AGENT_MODEL_NOT_CONFIGURED,
    SESSION_NOT_FOUND,
    SESSION_BUSY,
    SESSION_INITIALIZATION_FAILED,
    SESSION_DELETE_FAILED,
    INVALID_EVENT_REQUEST,
    EVENT_ACCEPTANCE_FAILED,
    SESSION_EXECUTION_FAILED,
    INVALID_EVENT_LIST_QUERY,
    EVENT_LIST_FAILED,
    INVALID_MODEL_REQUEST,
    INVALID_THINKING_REQUEST,
    MODEL_NOT_AVAILABLE,
    THINKING_NOT_SUPPORTED,
    IF_MATCH_REQUIRED,
    SESSION_VERSION_MISMATCH,
    SESSION_MODEL_UPDATE_FAILED,
    SESSION_THINKING_UPDATE_FAILED,
    INVALID_STEER_REQUEST,
    INVALID_FOLLOW_UP_REQUEST,
    SESSION_NOT_RUNNING,
    STEER_ACCEPTANCE_FAILED,
    FOLLOW_UP_ACCEPTANCE_FAILED,
    SESSION_ABORT_FAILED,
    RUNTIME_CAPACITY_EXCEEDED,
    CONTROL_QUEUE_FULL,
    MANAGER_UNAVAILABLE,
    INTERNAL_ERROR;

    public String messageKey() {
        return "runtime.error." + name().toLowerCase(java.util.Locale.ROOT);
    }
}
